# Generated by Django 5.1.3 on 2024-11-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cagur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=255)),
                ('pendidikan', models.CharField(max_length=255)),
                ('ipk', models.CharField(max_length=255)),
                ('pengalaman_mengajar', models.CharField(max_length=255)),
                ('umur', models.CharField(max_length=255)),
                ('psikotes', models.CharField(max_length=255)),
                ('sertifikasi_keahlian', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cagur',
            },
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap', models.IntegerField()),
                ('bobot_nilai', models.DecimalField(decimal_places=1, max_digits=8)),
                ('keterangan', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gap',
            },
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis', models.CharField(choices=[('Core Factor', 'Core Factor'), ('Secondary Factor', 'Secondary Factor')], max_length=20)),
            ],
            options={
                'db_table': 'kriteria',
            },
        ),
        migrations.CreateModel(
            name='NilaiProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_profil', models.PositiveIntegerField()),
                ('cagur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.cagur')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.kriteria')),
            ],
            options={
                'db_table': 'nilai_profil',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('cagur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cagur.nilaiprofil')),
                ('total_nilai', models.DecimalField(decimal_places=4, max_digits=8)),
                ('rank', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='SubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('nilai', models.SmallIntegerField()),
                ('selected', models.BooleanField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kriteria', to='cagur.kriteria')),
            ],
            options={
                'db_table': 'sub_kriteria',
            },
        ),
        migrations.AddField(
            model_name='nilaiprofil',
            name='sub_kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.subkriteria'),
        ),
        migrations.CreateModel(
            name='PerhitunganGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_profil', models.IntegerField()),
                ('gap', models.IntegerField()),
                ('bobot_gap', models.DecimalField(decimal_places=1, max_digits=8)),
                ('cagur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.nilaiprofil')),
                ('sub_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.subkriteria')),
            ],
            options={
                'db_table': 'perhitungan_gap',
                'unique_together': {('cagur', 'sub_kriteria')},
            },
        ),
        migrations.CreateModel(
            name='PerhitunganAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_nilai', models.DecimalField(decimal_places=1, max_digits=8)),
                ('rata_rata', models.DecimalField(decimal_places=4, max_digits=8)),
                ('total_rata_rata', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cagur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.nilaiprofil')),
                ('sub_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.subkriteria')),
            ],
            options={
                'db_table': 'perhitungan_akhir',
                'unique_together': {('cagur', 'sub_kriteria')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='nilaiprofil',
            unique_together={('cagur', 'kriteria', 'sub_kriteria')},
        ),
        migrations.CreateModel(
            name='IdealProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_ideal', models.PositiveIntegerField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.kriteria')),
                ('sub_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cagur.subkriteria')),
            ],
            options={
                'db_table': 'ideal_profil',
                'unique_together': {('kriteria', 'sub_kriteria')},
            },
        ),
    ]
